version: '3'
services:
  web:
    #stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
    ports:
      - '3000:80'
    volumes:
      - .:/app
      - /app/node_modules
  tests:
    #stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
