name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Checkout
        run: actions/checkout@v2
      -
        name: Docker Build Test
        run:  docker build -f Dockerfile.dev -t ankurgoyal9/frontendreact:test .
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ankurgoyal9
          password: Success99
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ankurgoyal9/frontendreact:latest
