name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Build Test
        run:  docker build -f Dockerfile.dev -t ankurgoyal9/frontendreact:test .
      -
        name: Docker Run Test
        run: docker run -e CI=true ankurgoyal9/frontendreact:test npm run test
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ankurgoyal9
          password: Success99
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ankurgoyal9/frontendreact:latest
      -ßß
        name: Docker Build Latest
        run:  docker build -f Dockerfile -t ankurgoyal9/frontendreact:latest .

      -
        name: Generate Deployment Package
        run: zip -r deploy.zip *
      -
        name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: AKIARZLUVJHX2Y7LRVNV
          aws_secret_key: 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
          application_name: frontendreact
          environment_name: Frontendreact-env
          version_label: "frontendreact-${{ steps.format-time.outputs.replaced }}"
          region: ap-south-1
          deployment_package: deploy.zip
